/* CSS */
import "./globals.css";

import { CSSProperties, useEffect, useMemo } from "react";
import { Raleway, Cookie } from "next/font/google";

/* Hooks */
import { Navigation } from "@/layouts/navigation";
import { SideEffects } from "./sideeffect";

/* Fonts */
const cookie = Cookie({
  subsets: ["latin"],
  display: "swap",
  variable: "--cookie-font",
  weight: ["400"],
});

const raleway = Raleway({
  subsets: ["latin"],
  display: "swap",
  variable: "--raleway-font",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
type Props = {
  children: React.ReactNode;
};

export default function RootLayout(props: Props) {
  const { children } = props;

  const fontVariables = useMemo(
    () =>
      ({
        "--cookie-font": cookie.style.fontFamily,
        "--raleway-font": raleway.style.fontFamily,
      } as unknown as CSSProperties),
    []
  );

  return (
    <html lang="en" style={fontVariables}>
      <SideEffects />
      <body className="bg-base-100 !pointer-events-auto transition-all duration-200 ease-linear">
        <Navigation />
        {children}
      </body>
    </html>
  );
}
